[book]
authors = ["Optimism Contributors"]
language = "en"
multilingual = false
src = "src"
title = "OP Deployer Book"

[output.html]
site-url = "/op-deployer/"
git-repository-url = "https://github.com/ethereum-optimism/optimism/tree/develop/op-deployer/book"
edit-url-template = "https://github.com/ethereum-optimism/optimism/tree/develop/op-deployer/book/{path}"
additional-css = ["custom.css"]
