[chain]
preset = 420

[rpcs]
l1-rpc = "${INDEXER_RPC_URL_L1}"
l2-rpc = "${INDEXER_RPC_URL_L2}"

[db]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "postgres"

[api]
host = "127.0.0.1"
port = 8080

[metrics]
host = "127.0.0.1"
port = 7300

