[profile.default]
src = 'contracts'
out = 'forge-artifacts'
optimizer = true
optimizer_runs = 999999

remappings = [
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@rari-capital/solmate/=node_modules/@rari-capital/solmate',
  "@cwia/=node_modules/clones-with-immutable-args/src",
  'forge-std/=node_modules/forge-std/src',
  'ds-test/=node_modules/ds-test/src'
]
extra_output = ['devdoc', 'userdoc', 'metadata', 'storageLayout']
bytecode_hash = 'none'
build_info = true
build_info_path = 'artifacts/build-info'
ffi = true
fuzz_runs = 16
# PNPM symlinks all node_modules from the monorepo root
allow_paths = ["../../node_modules", "./**"]

fs_permissions = [
  { 'access'='read-write', 'path'='./.resource-metering.csv' },
  { 'access'='read-write', 'path'='./deployments/' },
  { 'access'='read', 'path'='./deploy-config/' },
  { 'access'='read', 'path'='./broadcast/' },
  { access = 'read', path = './forge-artifacts/' },
]

[profile.ci]
fuzz_runs = 512
